%% Convert files generated by Systemvue to ModuRatC format.

%It is assumed that the original files had sampling frequency 
%of 2 MHz. For the simulations, Fs_bb=20 MHz will be used. So, the code
%below adopt a upsampling factor of 10.
L=10; %resample factor

outputPath=ff.myBasebandCenvTimeDomainDir; %output directory for files

ratID{1}='gsm';
ratID{2}='lte';
ratID{3}='wcdma';
for rat=1:3 %process all signals
    load(['externalFiles' filesep ratID{rat} '_3_reali_bb.mat']);
    fileCounter=1;
    for i=1:3
        eval(['x=' ratID{rat} '_3_reali_bb(:,i);']);
        x=resample(x,L,1);
        numOfOutputFiles=floor(length(x)/dsp.minNumSamplesBBSignals);
        for j=1:numOfOutputFiles
            %pwelch(x); pause
            %outputFileName=[outputPath ratID{rat} 'Fs' num2str(dsp.Fs_bb/1e3) ...
            %    'kHzBw' num2str(bandwidths(rat)/1e3) 'kHz_' num2str(fileCounter) '.' ff.basebandEnvelopesFileExtension];
            outputFileName=[outputPath ratID{rat} '_' num2str(fileCounter) '.' ff.basebandEnvelopesFileExtension];
            startSample = (j-1)*dsp.minNumSamplesBBSignals+1;
            endSample = startSample + dsp.minNumSamplesBBSignals - 1;
            write_complex_binary(outputFileName, x(startSample:endSample));
            disp(['Wrote ' outputFileName])
            fileCounter = fileCounter+1;
        end
    end
end
